  https://testandnotes.com/about
  https://testandnotes.com/contact
  https://testandnotes.com/logout
  https://testandnotes.com/page
  https://testandnotes.com/plans
  https://testandnotes.com/test
  https://testandnotes.com/start-test

  https://testandnotes.com/resetpassword
  https://testandnotes.com/resetpassword_creater
  https://testandnotes.com/resetpassword_franchise
  https://testandnotes.com/resetpassword_publisher
  https://testandnotes.com/resetpassword_student

  https://testandnotes.com/administrator
  https://testandnotes.com/administrator/books
  https://testandnotes.com/administrator/books/add
  https://testandnotes.com/administrator/corporate-enquiry
  https://testandnotes.com/administrator/course-detail-master
  https://testandnotes.com/administrator/franchise
  https://testandnotes.com/administrator/login
  https://testandnotes.com/administrator/material
  https://testandnotes.com/administrator/material/add
  https://testandnotes.com/administrator/material/store
  https://testandnotes.com/administrator/plan
  https://testandnotes.com/administrator/plan/add
  https://testandnotes.com/administrator/profile
  https://testandnotes.com/administrator/questions-bank/add
  https://testandnotes.com/administrator/questions-bank/import
  https://testandnotes.com/administrator/questions-bank/list
  https://testandnotes.com/administrator/settings/dashboard
  https://testandnotes.com/administrator/settings/delete-number
  https://testandnotes.com/administrator/settings/manage_home
  https://testandnotes.com/administrator/settings/no-otp-numbers
  https://testandnotes.com/administrator/settings/pdf-list
  https://testandnotes.com/administrator/test
  https://testandnotes.com/administrator/test/add
  https://testandnotes.com/administrator/test/attempt
  https://testandnotes.com/administrator/test/category/add
  https://testandnotes.com/administrator/test/category/list
  https://testandnotes.com/administrator/test/category/process
  https://testandnotes.com/administrator/test/eductaion-type
  https://testandnotes.com/administrator/test/subjects
  https://testandnotes.com/administrator/users/add

  https://testandnotes.com/contributor
  https://testandnotes.com/contributor/login
  https://testandnotes.com/corporate-enquiry

  https://testandnotes.com/institute
  https://testandnotes.com/institute-login
  https://testandnotes.com/institute-signup
  https://testandnotes.com/institute/management
  https://testandnotes.com/institute/management/creater
  https://testandnotes.com/institute/management/creater/material
  https://testandnotes.com/institute/management/creater/material/add
  https://testandnotes.com/institute/management/creater/material/store
  https://testandnotes.com/institute/management/creater/test
  https://testandnotes.com/institute/management/manager
  https://testandnotes.com/institute/management/manager/test
  https://testandnotes.com/institute/management/manager/test/add
  https://testandnotes.com/institute/management/material
  https://testandnotes.com/institute/management/material/add
  https://testandnotes.com/institute/management/material/store
  https://testandnotes.com/institute/management/profile
  https://testandnotes.com/institute/management/publisher
  https://testandnotes.com/institute/management/publisher/material
  https://testandnotes.com/institute/management/publisher/material/add
  https://testandnotes.com/institute/management/publisher/material/store
  https://testandnotes.com/institute/management/publisher/test
  https://testandnotes.com/institute/profile
  https://testandnotes.com/institute/settings/dashboard
  https://testandnotes.com/institute/test
  https://testandnotes.com/institute/test/add
  https://testandnotes.com/institute/test/attempt
  https://testandnotes.com/institute/user/add
  https://testandnotes.com/institute/users

  https://testandnotes.com/student
  https://testandnotes.com/student/attempt
  https://testandnotes.com/student/material/show
  https://testandnotes.com/student/material/showgk
  https://testandnotes.com/student/material/showvideo
  https://testandnotes.com/student/plan
  https://testandnotes.com/student/plan/payment-failed
  https://testandnotes.com/student/plan/payment-success
  https://testandnotes.com/student/plan/purchased
  https://testandnotes.com/student/profile
  https://testandnotes.com/student/settings/dashboard
  https://testandnotes.com/student/test