  https://testandnotes.com/about
  https://testandnotes.com/admin
  https://testandnotes.com/administrator
  https://testandnotes.com/administrator/books
  https://testandnotes.com/administrator/books/add
  https://testandnotes.com/administrator/books/delete/{id}
  https://testandnotes.com/administrator/books/view/{id}
  https://testandnotes.com/administrator/corporate-enquiry
  https://testandnotes.com/administrator/corporate-enquiry/delete/{id}
  https://testandnotes.com/administrator/corporate-enquiry/type/{type}
  https://testandnotes.com/administrator/corporate-enquiry/view/{id}
  https://testandnotes.com/administrator/course-detail-master
  https://testandnotes.com/administrator/franchise
  https://testandnotes.com/administrator/franchise/delete/{id}
  https://testandnotes.com/administrator/franchise/status/{status}
  https://testandnotes.com/administrator/franchise/type/{type}
  https://testandnotes.com/administrator/franchise/view/type/{type}
  https://testandnotes.com/administrator/franchise/view/{id}
  https://testandnotes.com/administrator/franchise/viewmaterial/{id}
  https://testandnotes.com/administrator/franchise/viewstudentusers/{id}
  https://testandnotes.com/administrator/franchise/viewusers/{id}
  https://testandnotes.com/administrator/login
  https://testandnotes.com/administrator/material
  https://testandnotes.com/administrator/material/add
  https://testandnotes.com/administrator/material/add/{id}
  https://testandnotes.com/administrator/material/download/{file}
  https://testandnotes.com/administrator/material/getpackage/{education_type_id}/{class_group_exam_id}/{value}
  https://testandnotes.com/administrator/material/is_featured/{plan_id}/{status}
  https://testandnotes.com/administrator/material/store
  https://testandnotes.com/administrator/password-reset/{email}/{code}
  https://testandnotes.com/administrator/plan
  https://testandnotes.com/administrator/plan/add
  https://testandnotes.com/administrator/plan/add/{id}
  https://testandnotes.com/administrator/plan/is_featured/{plan_id}/{status}
  https://testandnotes.com/administrator/profile
  https://testandnotes.com/administrator/questions-bank/add
  https://testandnotes.com/administrator/questions-bank/import
  https://testandnotes.com/administrator/questions-bank/list/{type?}
  https://testandnotes.com/administrator/questions-bank/show/{id}
  https://testandnotes.com/administrator/questions-bank/update/{id}
  https://testandnotes.com/administrator/settings/dashboard
  https://testandnotes.com/administrator/settings/delete-number
  https://testandnotes.com/administrator/settings/manage_home
  https://testandnotes.com/administrator/settings/no-otp-numbers
  https://testandnotes.com/administrator/settings/pdf-list
  https://testandnotes.com/administrator/settings/slider_delete/{image}
  https://testandnotes.com/administrator/test
  https://testandnotes.com/administrator/test/add
  https://testandnotes.com/administrator/test/attempt
  https://testandnotes.com/administrator/test/category/add
  https://testandnotes.com/administrator/test/category/delete/{id}
  https://testandnotes.com/administrator/test/category/edit/{id}
  https://testandnotes.com/administrator/test/category/list
  https://testandnotes.com/administrator/test/category/process
  https://testandnotes.com/administrator/test/eductaion-type
  https://testandnotes.com/administrator/test/feature/{id}
  https://testandnotes.com/administrator/test/publish/{test_id}
  https://testandnotes.com/administrator/test/section/question/{test_id}/{section_id}
  https://testandnotes.com/administrator/test/section/questionadd/{test_id}/{section_id}
  https://testandnotes.com/administrator/test/section/{test_id}
  https://testandnotes.com/administrator/test/section/{test_id}/add-update
  https://testandnotes.com/administrator/test/student-list/{test_id}
  https://testandnotes.com/administrator/test/subjects
  https://testandnotes.com/administrator/test/update/{test_id}
  https://testandnotes.com/administrator/users/add
  https://testandnotes.com/administrator/users/delete/{id}
  https://testandnotes.com/administrator/users/type/{type}/{franchise?}
  https://testandnotes.com/administrator/users/view/{id}
  https://testandnotes.com/contact
  https://testandnotes.com/contributor
  https://testandnotes.com/contributor/login
  https://testandnotes.com/corporate-enquiry
  https://testandnotes.com/course/{edu_type}/{class}
  https://testandnotes.com/institute
  https://testandnotes.com/institute-login
  https://testandnotes.com/institute-signup
  https://testandnotes.com/institute/management
  https://testandnotes.com/institute/management/creater
  https://testandnotes.com/institute/management/creater/material
  https://testandnotes.com/institute/management/creater/material/add
  https://testandnotes.com/institute/management/creater/material/add/{id}
  https://testandnotes.com/institute/management/creater/material/download/{file}
  https://testandnotes.com/institute/management/creater/material/store
  https://testandnotes.com/institute/management/creater/test
  https://testandnotes.com/institute/management/creater/test/publish/{test_id}
  https://testandnotes.com/institute/management/creater/test/section/question/{test_id}/{section_id}
  https://testandnotes.com/institute/management/creater/test/section/questionadd/{test_id}/{section_id}
  https://testandnotes.com/institute/management/creater/test/section/{test_id}
  https://testandnotes.com/institute/management/creater/test/section/{test_id}/add-update
  https://testandnotes.com/institute/management/creater/test/update/{test_id}
  https://testandnotes.com/institute/management/manager
  https://testandnotes.com/institute/management/manager/test
  https://testandnotes.com/institute/management/manager/test/add
  https://testandnotes.com/institute/management/manager/test/publish/{test_id}
  https://testandnotes.com/institute/management/manager/test/section/question/{test_id}/{section_id}
  https://testandnotes.com/institute/management/manager/test/section/questionadd/{test_id}/{section_id}
  https://testandnotes.com/institute/management/manager/test/section/{test_id}
  https://testandnotes.com/institute/management/manager/test/section/{test_id}/add-update
  https://testandnotes.com/institute/management/manager/test/update/{test_id}
  https://testandnotes.com/institute/management/material
  https://testandnotes.com/institute/management/material/add
  https://testandnotes.com/institute/management/material/add/{id}
  https://testandnotes.com/institute/management/material/download/{file}
  https://testandnotes.com/institute/management/material/store
  https://testandnotes.com/institute/management/profile
  https://testandnotes.com/institute/management/publisher
  https://testandnotes.com/institute/management/publisher/material
  https://testandnotes.com/institute/management/publisher/material/add
  https://testandnotes.com/institute/management/publisher/material/add/{id}
  https://testandnotes.com/institute/management/publisher/material/download/{file}
  https://testandnotes.com/institute/management/publisher/material/store
  https://testandnotes.com/institute/management/publisher/test
  https://testandnotes.com/institute/management/publisher/test/publish/{test_id}
  https://testandnotes.com/institute/management/publisher/test/section/question/{test_id}/{section_id}
  https://testandnotes.com/institute/management/publisher/test/section/questionadd/{test_id}/{section_id}
  https://testandnotes.com/institute/management/publisher/test/section/{test_id}
  https://testandnotes.com/institute/management/publisher/test/section/{test_id}/add-update
  https://testandnotes.com/institute/management/publisher/test/update/{test_id}
  https://testandnotes.com/institute/password-reset/{email}/{code}
  https://testandnotes.com/institute/profile
  https://testandnotes.com/institute/settings/dashboard
  https://testandnotes.com/institute/test
  https://testandnotes.com/institute/test/add
  https://testandnotes.com/institute/test/attempt
  https://testandnotes.com/institute/test/publish/{test_id}
  https://testandnotes.com/institute/test/section/question/{test_id}/{section_id}
  https://testandnotes.com/institute/test/section/questionadd/{test_id}/{section_id}
  https://testandnotes.com/institute/test/section/{test_id}
  https://testandnotes.com/institute/test/section/{test_id}/add-update
  https://testandnotes.com/institute/test/student-list/{test_id}
  https://testandnotes.com/institute/test/update/{test_id}
  https://testandnotes.com/institute/user/add
  https://testandnotes.com/institute/user/view/{id}
  https://testandnotes.com/institute/users
  https://testandnotes.com/institute/users/{type}
  https://testandnotes.com/logout
  https://testandnotes.com/page
  https://testandnotes.com/plans
  https://testandnotes.com/question-paper/{name}
  https://testandnotes.com/reset-password/{studentid}/{resetid}
  https://testandnotes.com/resetpassword
  https://testandnotes.com/resetpassword_creater
  https://testandnotes.com/resetpassword_franchise
  https://testandnotes.com/resetpassword_publisher
  https://testandnotes.com/resetpassword_student
  https://testandnotes.com/sanctum/csrf-cookie
  https://testandnotes.com/show-result/{name}/{test_id}
  https://testandnotes.com/show-test-response/{name}/{test_id}
  https://testandnotes.com/start-test
  https://testandnotes.com/start-test/{name}
  https://testandnotes.com/student
  https://testandnotes.com/student/attempt
  https://testandnotes.com/student/material/download/{file}
  https://testandnotes.com/student/material/show
  https://testandnotes.com/student/material/showgk
  https://testandnotes.com/student/material/showvideo
  https://testandnotes.com/student/material/viewmaterial/{file}
  https://testandnotes.com/student/package_manage/{id}
  https://testandnotes.com/student/password-reset/{code}
  https://testandnotes.com/student/plan
  https://testandnotes.com/student/plan/checkout/{id}
  https://testandnotes.com/student/plan/payment-failed
  https://testandnotes.com/student/plan/payment-success
  https://testandnotes.com/student/plan/purchased
  https://testandnotes.com/student/profile
  https://testandnotes.com/student/settings/dashboard
  https://testandnotes.com/student/test
  https://testandnotes.com/student/test/dashboard_gyanology_list/{cat?}
  https://testandnotes.com/student/test/question-paper/{test_id}
  https://testandnotes.com/student/test/section/question/{test_id}/{section_id}
  https://testandnotes.com/student/test/section/questionadd/{test_id}/{section_id}
  https://testandnotes.com/student/test/section/{test_id}
  https://testandnotes.com/student/test/section/{test_id}/add-update
  https://testandnotes.com/student/test/show-result/{student_id}/{test_id}
  https://testandnotes.com/student/test/start-test/{test_id}
  https://testandnotes.com/student/test/{name}
  https://testandnotes.com/student/verifynumber/{mobile_number}
  https://testandnotes.com/student/verifyotp/{mobile_number}/{mobile_otp}
  https://testandnotes.com/test
  https://testandnotes.com/test/{name}

